In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import matplotlib.pyplot as plt
import MESS
import numpy as np
import pandas as pd

from IPython.display import display

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Load the Weevil data

In [2]:
m_df = pd.read_csv("/home/isaac/SGD_empirical/empirical_weevils/mauritius.dat", header=0, index_col=0)
r_df = pd.read_csv("/home/isaac/SGD_empirical/empirical_weevils/reunion.dat", header=0)
print(len(m_df), len(r_df))
print(np.sum(m_df["abundance"]))
print(np.sum(r_df["abundance"]))
display(m_df[:2])
display(r_df[:2])

(26, 27)
343.0
539.0

                               pi  abundance
Cratopopsis_impressus    0.043741        4.0
Cratopopsis_mauritianus  0.002413        5.0

             Unnamed: 0        pi  abundance
0  Cratopopsis_alluaudi  0.019174       12.0
1  Cratopopsis_antiquus  0.017928       11.0

# Select the best model

In [3]:
simfile = "/home/isaac/Continuosity/MESS/analysis/full-parameter-estimation/SIMOUT.txt"

for isl, df in zip(["Mauritius", "Reunion"], [m_df, r_df]):
    cla = MESS.inference.Classifier(empirical_df=df, simfile=simfile, algorithm="rf")
    est, proba = cla.predict(select_features=True, param_search=True, quick=False, verbose=False)
    display(isl, est, proba)
    display(cla.feature_importances())

'Mauritius'

         community_assembly_model
estimate              competition

                          competition  filtering  neutral
community_assembly_model      0.62713      0.035  0.33787

                           S  abund_h1  abund_h2  abund_h3  abund_h4    pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3    SGD_4
Feature importance  0.099788   0.14938  0.062739  0.058545  0.061017  0.06049  0.052943  0.048282  0.044997  0.040913  0.046475     0.034805     0.033153   0.003968  0.022838          0.035955  0.080867  0.017482  0.018006  0.016066  0.01129

'Reunion'

         community_assembly_model
estimate              competition

                          competition  filtering   neutral
community_assembly_model     0.562917   0.121458  0.315625

                           S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3   pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4
Feature importance  0.099212  0.148348  0.064098  0.057053  0.059636  0.061976  0.053578  0.048451  0.0424  0.040846  0.047142     0.035329     0.033068      0.004  0.024074          0.037547  0.080201  0.015501  0.018526  0.016871  0.012143

# Estimate parameters

In [4]:
for isl, df in zip(["Mauritius", "Reunion"], [m_df, r_df]):
    rgr = MESS.inference.Regressor(empirical_df=df, simfile=simfile, algorithm="rfq")
    #rgr.set_targets(target_list=["alpha", "_lambda"])

    est = rgr.predict(select_features=False, param_search=False, quick=True, verbose=True)
    display(isl, est, rgr.feature_importances())

Calculating prediction interval(s)

'Mauritius'

              alpha        J_m  ecological_strength        m  speciation_prob  _lambda
estimate     4133.7  2786608.9             5.017166  0.00352         0.002339   0.9044
lower 0.025  3154.0   238272.0             1.584490  0.00110         0.000133   0.8420
upper 0.975  4819.0  4761646.0             9.417180  0.00696         0.009060   1.0000

                            S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha                0.024141  0.079662  0.023055  0.024502  0.027834  0.025932  0.015152  0.014374  0.015836  0.196868  0.027456     0.031306     0.032153   0.006792  0.248432    0.0          0.062801  0.038411  0.014451  0.019239  0.015831  0.011189  0.013083  0.008838  0.007651  0.007934  0.007073
J_m                  0.040737  0.059893  0.040949  0.037826  0.045567  0.053207  0.035793  0.031786  0.045524  0.046576  0.058908     0.054844     0.068147   0.002343  0.017556    0.0          0.102080  0.042865  0.025117  0.030752  0.029733  0.025768  0.029443  0.021709  0.019351  0.016237  0.017290
ecological_strength  0.039587  0.078386  0.043561  0.038859  0.041785  0.039917  0.029288  0.027251  0.033282  0.043894  0.058810     0.062996     0.068214   0.003717  0.022283    0.0          0.099707  0.050463  0.025973  0.030874  0.032337  0.030084  0.029067  0.023392  0.015921  0.014257  0.016095
m                    0.220906  0.066577  0.042303  0.033054  0.041176  0.028636  0.019815  0.021048  0.019772  0.037585  0.057939     0.036068     0.039327   0.001556  0.011565    0.0          0.094064  0.056885  0.025056  0.026090  0.025909  0.020204  0.021568  0.013955  0.013373  0.013522  0.012048
speciation_prob      0.239384  0.178061  0.020156  0.027563  0.070639  0.024273  0.013142  0.010247  0.015016  0.055778  0.060968     0.010591     0.015263   0.000340  0.026867    0.0          0.024012  0.146439  0.004199  0.013093  0.009358  0.004950  0.010239  0.005417  0.005903  0.002638  0.005466
_lambda              0.008808  0.037639  0.024210  0.028647  0.760683  0.005651  0.003861  0.002569  0.005893  0.012621  0.019945     0.010555     0.007154   0.002130  0.003411    0.0          0.015959  0.016888  0.006356  0.003203  0.006296  0.003114  0.004839  0.003342  0.002616  0.002306  0.001301

Calculating prediction interval(s)

'Reunion'

              alpha        J_m  ecological_strength         m  speciation_prob   _lambda
estimate     3859.5  3863767.1             4.474648  0.003577          0.00132  0.882873
lower 0.025  2612.0  1759170.0             1.417260  0.001819          0.00013  0.776000
upper 0.975  4812.0  4666710.0             9.842120  0.006730          0.00463  0.993000

                            S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha                0.020954  0.084039  0.028767  0.022979  0.023981  0.025437  0.015799  0.011682  0.018912  0.222298  0.028493     0.035649     0.034360   0.005132  0.215722    0.0          0.068707  0.029706  0.013350  0.016166  0.015283  0.013876  0.013292  0.010129  0.009072  0.008495  0.007721
J_m                  0.050073  0.070752  0.042901  0.041046  0.043436  0.043014  0.038397  0.031076  0.044192  0.039291  0.052055     0.059574     0.058603   0.003344  0.020218    0.0          0.097639  0.044651  0.028756  0.029193  0.031437  0.030211  0.029815  0.020963  0.017105  0.016182  0.016074
ecological_strength  0.048040  0.073952  0.045558  0.044654  0.041432  0.044653  0.032126  0.027570  0.037972  0.045342  0.056601     0.057165     0.061495   0.003164  0.021001    0.0          0.098054  0.039732  0.028183  0.029263  0.035135  0.031252  0.027787  0.022173  0.016330  0.015991  0.015376
m                    0.235656  0.064986  0.038594  0.031210  0.039393  0.032578  0.025302  0.018937  0.022797  0.032217  0.056039     0.045291     0.045797   0.001586  0.011412    0.0          0.097583  0.040043  0.019559  0.024447  0.025877  0.021123  0.018596  0.014016  0.013627  0.012220  0.011116
speciation_prob      0.216856  0.177839  0.026255  0.018353  0.070949  0.040793  0.011741  0.010248  0.011810  0.064316  0.055742     0.012335     0.016450   0.000054  0.015941    0.0          0.026276  0.157653  0.004603  0.012036  0.010313  0.005950  0.011989  0.006183  0.004432  0.005004  0.005880
_lambda              0.010575  0.038413  0.028353  0.061216  0.721704  0.007486  0.003864  0.004762  0.004200  0.011788  0.021678     0.007998     0.011372   0.001810  0.004045    0.0          0.018602  0.012370  0.004045  0.003084  0.004715  0.003636  0.003999  0.002217  0.002280  0.003235  0.002555

## Save regressor to file/model to file

In [150]:
rgr.feature_importances()
#rgr.model_by_target

                S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha    0.015795  0.066961  0.018036  0.012658  0.025727  0.027068  0.009332  0.002480  0.002773  0.275834  0.008189     0.022957     0.010469   0.004996  0.369852    0.0          0.059932  0.050365  0.001897  0.001806  0.002297  0.002108  0.004731  0.002443  0.000570  0.000000  0.000721
_lambda  0.006080  0.018718  0.006266  0.040721  0.859859  0.003194  0.001113  0.004015  0.001348  0.009954  0.010465     0.003409     0.005999   0.001550  0.002724    0.0          0.006535  0.013376  0.001096  0.000300  0.000758  0.000035  0.000916  0.000294  0.000857  0.000169  0.000251

# Trash below here

In [56]:
simfile = "/home/isaac/Continuosity/MESS/analysis/full-parameter-estimation/SIMOUT.txt"

cla = MESS.inference.Classifier(empirical_df=sp_df, simfile=simfile, algorithm="rf", verbose=True)
cla._base_model
cla.y[:2]
#rgr.set_targets(target_list="_lambda")
#rgr.predict(select_features=True, quick=False, verbose=True)

Got empirical summary statistics:     S   abund_h1   abund_h2   abund_h3  abund_h4      pi_h1      pi_h2      pi_h3      pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi   iqr_pi  trees  abundance_pi_cor  SGD_0  SGD_1  SGD_2  SGD_3  SGD_4  SGD_5  SGD_6  SGD_7  SGD_8  SGD_9
0  57  22.334174  14.092503  10.622744  8.877024  27.956422  21.660417  19.178423  17.853145  0.008283  0.010581      1.41016     0.756963   0.003258  0.01004      0          0.413119     32      7      5      0      2      4      1      3      1      2

  community_assembly_model
0                  neutral
1                  neutral

In [218]:
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor
abc = AdaBoostClassifier()
abc.fit(cla.X, cla.y)
abc.predict(cla.empirical_sumstats)

abr = AdaBoostRegressor()
abr.fit(rgr.X, rgr.y["alpha"])
abr.predict(rgr.empirical_sumstats)

array([4128.40555556])