In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import matplotlib.pyplot as plt
import MESS
import numpy as np
import pandas as pd

from IPython.display import display

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Load the Weevil data

In [5]:
m_df = pd.read_csv("/home/isaac/SGD_empirical/empirical_weevils/mauritius.dat", header=0, index_col=0)
r_df = pd.read_csv("/home/isaac/SGD_empirical/empirical_weevils/reunion.dat", header=0)
print(len(m_df), len(r_df))
print(np.sum(m_df["abundance"]))
print(np.sum(r_df["abundance"]))
display(m_df[:2])
display(r_df[:2])

(26, 27)
343.0
539.0

                               pi  abundance
Cratopopsis_impressus    0.043741        4.0
Cratopopsis_mauritianus  0.002413        5.0

             Unnamed: 0        pi  abundance
0  Cratopopsis_alluaudi  0.019174       12.0
1  Cratopopsis_antiquus  0.017928       11.0

# Select the best model

In [6]:
simfile = "/home/isaac/Continuosity/MESS/analysis/full-parameter-estimation/SIMOUT.txt"

for isl, df in zip(["Mauritius", "Reunion"], [m_df, r_df]):
    cla = MESS.inference.Classifier(empirical_df=df, simfile=simfile, algorithm="rf")
    est, proba = cla.predict(select_features=True, param_search=True, quick=False, verbose=False)
    display(isl, est, proba)
    display(cla.feature_importances())

'Mauritius'

         community_assembly_model
estimate                  neutral

                          competition  filtering   neutral
community_assembly_model     0.005403     0.0318  0.962797

                           S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4
Feature importance  0.043541  0.133713  0.070257  0.066239  0.067278  0.045952  0.038163  0.033975  0.033077  0.074481  0.101564     0.038031      0.03741   0.009474  0.043555          0.047397  0.039515  0.033648  0.015198  0.015314  0.012218

'Reunion'

         community_assembly_model
estimate                  neutral

                          competition  filtering   neutral
community_assembly_model     0.004415   0.025011  0.970574

                           S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4
Feature importance  0.043009   0.13766  0.071098  0.066254  0.066673  0.043132  0.037892  0.033178  0.032162  0.072352  0.107136     0.037458     0.036329   0.008867  0.047878          0.045406  0.039489  0.033857  0.014717  0.014384  0.011068

# Estimate parameters

In [7]:
for isl, df in zip(["Mauritius", "Reunion"], [m_df, r_df]):
    rgr = MESS.inference.Regressor(empirical_df=df, simfile=simfile, algorithm="rfq")
    #rgr.set_targets(target_list=["alpha", "_lambda"])

    est = rgr.predict(select_features=False, param_search=False, quick=True, verbose=True)
    display(isl, est, rgr.feature_importances())

Calculating prediction interval(s)

'Mauritius'

              alpha       J_m  ecological_strength         m  speciation_prob   _lambda
estimate     8011.0  500000.0             4.758182  0.004992         0.000948  0.948994
lower 0.025  5778.0  500000.0             0.011070  0.001400         0.000510  0.855620
upper 0.975  9468.0  500000.0             8.836360  0.009920         0.002905  0.988630

                            S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha                0.028108  0.090454  0.037374  0.033956  0.039227  0.038757  0.025223  0.022545  0.026631  0.043919  0.049091     0.043140     0.044015   0.126377  0.058133    0.0          0.097607  0.070233  0.014016  0.020577  0.018280  0.014887  0.019812  0.010636  0.010662  0.007658  0.008682
J_m                  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000     0.000000     0.000000   0.000000  0.000000    0.0          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
ecological_strength  0.036663  0.098196  0.062202  0.045947  0.055112  0.033510  0.026122  0.028466  0.030703  0.044749  0.063815     0.058612     0.057346   0.009418  0.030243    0.0          0.095869  0.041853  0.020030  0.029020  0.027587  0.019438  0.025227  0.015692  0.015812  0.012221  0.016146
m                    0.040513  0.080440  0.046040  0.039684  0.047290  0.038971  0.034039  0.035349  0.047251  0.041924  0.072368     0.048710     0.050138   0.006932  0.026241    0.0          0.108550  0.079526  0.018442  0.020477  0.023195  0.018972  0.022778  0.016122  0.013218  0.011222  0.011609
speciation_prob      0.046356  0.057834  0.032542  0.026746  0.035546  0.024822  0.016968  0.018148  0.021415  0.045529  0.126100     0.036837     0.040035   0.003005  0.015193    0.0          0.078134  0.256650  0.013497  0.019068  0.017852  0.013529  0.018156  0.010445  0.009497  0.007676  0.008419
_lambda              0.026901  0.106800  0.041466  0.039772  0.402363  0.015008  0.010819  0.011181  0.013361  0.038588  0.042107     0.022703     0.023705   0.003408  0.012567    0.0          0.051382  0.073816  0.006495  0.008074  0.009830  0.008005  0.010987  0.005586  0.004203  0.005225  0.005651

Calculating prediction interval(s)

'Reunion'

              alpha       J_m  ecological_strength         m  speciation_prob   _lambda
estimate     8750.4  500000.0             1.457679  0.003436         0.000731  0.910992
lower 0.025  7048.0  500000.0             0.016360  0.001280         0.000510  0.780470
upper 0.975  9743.0  500000.0             4.977740  0.005657         0.001420  0.984950

                            S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha                0.027095  0.095279  0.039537  0.032032  0.038878  0.042120  0.024948  0.023008  0.024989  0.046097  0.048242     0.040660     0.043583   0.127357  0.055278    0.0          0.099163  0.068333  0.014676  0.018854  0.018287  0.014753  0.019707  0.011131  0.010015  0.007785  0.008194
J_m                  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000     0.000000     0.000000   0.000000  0.000000    0.0          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
ecological_strength  0.040445  0.100281  0.060115  0.046074  0.052513  0.036066  0.024934  0.026937  0.033250  0.043383  0.062277     0.055640     0.061547   0.007858  0.026748    0.0          0.099028  0.042493  0.020473  0.027003  0.027564  0.019202  0.024624  0.017804  0.015228  0.012759  0.015752
m                    0.039778  0.079604  0.045212  0.037271  0.044546  0.037803  0.031999  0.033014  0.046646  0.042145  0.073734     0.050453     0.054412   0.007570  0.026071    0.0          0.107869  0.080612  0.018185  0.022365  0.023698  0.022238  0.022283  0.015693  0.015119  0.011041  0.010638
speciation_prob      0.044032  0.058022  0.032750  0.027755  0.034639  0.027955  0.018604  0.017624  0.020684  0.045191  0.125785     0.035962     0.036384   0.002751  0.015289    0.0          0.073324  0.259444  0.013147  0.018783  0.018398  0.013480  0.020316  0.010956  0.009566  0.009615  0.009546
_lambda              0.026185  0.105021  0.042442  0.037863  0.403462  0.014502  0.013082  0.010748  0.012816  0.042197  0.041044     0.021433     0.022607   0.003008  0.013173    0.0          0.052865  0.070844  0.005853  0.007865  0.010019  0.008123  0.013042  0.005357  0.005102  0.005510  0.005837

## Save regressor to file/model to file

In [150]:
rgr.feature_importances()
#rgr.model_by_target

                S  abund_h1  abund_h2  abund_h3  abund_h4     pi_h1     pi_h2     pi_h3     pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi    iqr_pi  trees  abundance_pi_cor     SGD_0     SGD_1     SGD_2     SGD_3     SGD_4     SGD_5     SGD_6     SGD_7     SGD_8     SGD_9
alpha    0.015795  0.066961  0.018036  0.012658  0.025727  0.027068  0.009332  0.002480  0.002773  0.275834  0.008189     0.022957     0.010469   0.004996  0.369852    0.0          0.059932  0.050365  0.001897  0.001806  0.002297  0.002108  0.004731  0.002443  0.000570  0.000000  0.000721
_lambda  0.006080  0.018718  0.006266  0.040721  0.859859  0.003194  0.001113  0.004015  0.001348  0.009954  0.010465     0.003409     0.005999   0.001550  0.002724    0.0          0.006535  0.013376  0.001096  0.000300  0.000758  0.000035  0.000916  0.000294  0.000857  0.000169  0.000251

# Trash below here

In [56]:
simfile = "/home/isaac/Continuosity/MESS/analysis/full-parameter-estimation/SIMOUT.txt"

cla = MESS.inference.Classifier(empirical_df=sp_df, simfile=simfile, algorithm="rf", verbose=True)
cla._base_model
cla.y[:2]
#rgr.set_targets(target_list="_lambda")
#rgr.predict(select_features=True, quick=False, verbose=True)

Got empirical summary statistics:     S   abund_h1   abund_h2   abund_h3  abund_h4      pi_h1      pi_h2      pi_h3      pi_h4   mean_pi    std_pi  skewness_pi  kurtosis_pi  median_pi   iqr_pi  trees  abundance_pi_cor  SGD_0  SGD_1  SGD_2  SGD_3  SGD_4  SGD_5  SGD_6  SGD_7  SGD_8  SGD_9
0  57  22.334174  14.092503  10.622744  8.877024  27.956422  21.660417  19.178423  17.853145  0.008283  0.010581      1.41016     0.756963   0.003258  0.01004      0          0.413119     32      7      5      0      2      4      1      3      1      2

  community_assembly_model
0                  neutral
1                  neutral

In [ ]:
for isl, df in zip(["Mauritius", "Reunion"], [m_df, r_df]):
    cla = MESS.inference.Classifier(empirical_df=df, simfile=simfile, algorithm="rf")
    est, proba = cla.predict(select_features=True, param_search=True, quick=False, verbose=False)
    display(isl, est, proba)
    display(cla.feature_importances())
    rgr = MESS.inference.Regressor(empirical_df=df, simfile=simfile, algorithm="rfq")

    est = rgr.predict(select_features=False, param_search=False, quick=True, verbose=True)
    display(isl, est, rgr.feature_importances())